# Place in /etc/keyd/default.conf (or include from there) to remap
# the Piantor's LGUI (⌘ Cmd) key to LCtrl on Linux.
# This makes ⌘C send Ctrl+C, ⌘V send Ctrl+V, etc.
#
# Device ID 1d50:615e = Piantor Pro BT

[ids]
1d50:615e

[1d50:615e]
leftmeta = leftcontrol
